export const statsByRarity = [
  {
    key: "MAIN_STAT",
    label: "Main Stat",
    flat: true,
    values: {
      NORMAL: { min: 40, max: 60 },
      RARE: { min: 100, max: 150 },
      EPIC: { min: 200, max: 300 },
      UNIQUE: { min: 400, max: 700 },
      LEGENDARY: { min: 800, max: 1200 },
      MYSTIC: { min: 1500, max: 2500 },
    },
  },
  {
    key: "MAX_HP",
    label: "Max HP",
    flat: true,
    values: {
      NORMAL: { min: 1200, max: 1500 },
      RARE: { min: 1800, max: 3000 },
      EPIC: { min: 4500, max: 9000 },
      UNIQUE: { min: 15000, max: 30000 },
      LEGENDARY: { min: 35000, max: 65000 },
      MYSTIC: { min: 70000, max: 115000 },
    },
  },
  {
    key: "MAX_MP",
    label: "Max MP",
    flat: true,
    values: {
      NORMAL: { min: 30, max: 40 },
      RARE: { min: 50, max: 70 },
      EPIC: { min: 100, max: 150 },
      UNIQUE: { min: 200, max: 400 },
      LEGENDARY: { min: 500, max: 800 },
      MYSTIC: { min: 900, max: 1500 },
    },
  },
  {
    key: "ACCURACY",
    label: "Accuracy",
    flat: true,
    values: {
      NORMAL: { min: 2, max: 3 },
      RARE: { min: 4, max: 5 },
      EPIC: { min: 6, max: 8 },
      UNIQUE: { min: 10, max: 12 },
      LEGENDARY: { min: 14, max: 16 },
      MYSTIC: { min: 20, max: 25 },
    },
  },
  {
    key: "EVASION",
    label: "Evasion",
    flat: true,
    values: {
      NORMAL: { min: 2, max: 3 },
      RARE: { min: 4, max: 5 },
      EPIC: { min: 6, max: 8 },
      UNIQUE: { min: 10, max: 12 },
      LEGENDARY: { min: 14, max: 16 },
      MYSTIC: { min: 20, max: 25 },
    },
  },
  {
    key: "MP_REGEN",
    label: "MP Recovery Per Sec",
    flat: true,
    values: {
      NORMAL: { min: 3, max: 5 },
      RARE: { min: 6, max: 10 },
      EPIC: { min: 11, max: 20 },
      UNIQUE: { min: 21, max: 30 },
      LEGENDARY: { min: 40, max: 60 },
      MYSTIC: { min: 80, max: 150 },
    },
  },
  {
    key: "DAMAGE",
    label: "Damage",
    flat: false,
    values: {
      NORMAL: { void: "-" },
      RARE: { min: 3, max: 5 },
      EPIC: { min: 7, max: 10 },
      UNIQUE: { min: 12, max: 15 },
      LEGENDARY: { min: 18, max: 25 },
      MYSTIC: { min: 28, max: 40 },
    },
  },
  {
    key: "DEBUFF_TOLERANCE",
    label: "Debuff Tolerance",
    flat: true,
    values: {
      NORMAL: { void: "-" },
      RARE: { min: 4, max: 5 },
      EPIC: { min: 6, max: 8 },
      UNIQUE: { min: 10, max: 12 },
      LEGENDARY: { min: 14, max: 16 },
      MYSTIC: { min: 18, max: 25 },
    },
  },
  {
    key: "MIN_DAMAGE_MULT",
    label: "Min Damage Multiplier",
    flat: false,
    values: {
      NORMAL: { void: "-" },
      RARE: { void: "-" },
      EPIC: { min: 7, max: 10 },
      UNIQUE: { min: 12, max: 15 },
      LEGENDARY: { min: 18, max: 25 },
      MYSTIC: { min: 28, max: 40 },
    },
  },
  {
    key: "MAX_DAMAGE_MULT",
    label: "Max Damage Multiplier",
    flat: false,
    values: {
      NORMAL: { void: "-" },
      RARE: { void: "-" },
      EPIC: { min: 7, max: 10 },
      UNIQUE: { min: 12, max: 15 },
      LEGENDARY: { min: 18, max: 25 },
      MYSTIC: { min: 28, max: 40 },
    },
  },
  {
    key: "CRIT_RATE",
    label: "Critical Rate",
    flat: false,
    values: {
      NORMAL: { void: "-" },
      RARE: { void: "-" },
      EPIC: { min: 3, max: 6 },
      UNIQUE: { min: 7, max: 9 },
      LEGENDARY: { min: 10, max: 14 },
      MYSTIC: { min: 15, max: 20 },
    },
  },
  {
    key: "CRIT_RESIST",
    label: "Critical Resistance",
    flat: false,
    values: {
      NORMAL: { void: "-" },
      RARE: { void: "-" },
      EPIC: { min: 4.5, max: 9 },
      UNIQUE: { min: 10.5, max: 13.5 },
      LEGENDARY: { min: 15, max: 21 },
      MYSTIC: { min: 22.5, max: 30 },
    },
  },
  {
    key: "ATTACK_SPEED",
    label: "Attack Speed",
    flat: false,
    values: {
      NORMAL: { void: "-" },
      RARE: { void: "-" },
      EPIC: { void: "-" },
      UNIQUE: { min: 7, max: 9 },
      LEGENDARY: { min: 10, max: 14 },
      MYSTIC: { min: 15, max: 20 },
    },
  },
  {
    key: "DAMAGE_TAKEN_DECREASE",
    label: "Damage Taken Decrease",
    flat: false,
    values: {
      NORMAL: { void: "-" },
      RARE: { void: "-" },
      EPIC: { void: "-" },
      UNIQUE: { min: 2, max: 3 },
      LEGENDARY: { min: 4, max: 6 },
      MYSTIC: { min: 7, max: 10 },
    },
  },
  {
    key: "MESO_DROP",
    label: "Meso Drop",
    flat: false,
    values: {
      NORMAL: { void: "-" },
      RARE: { void: "-" },
      EPIC: { void: "-" },
      UNIQUE: { void: "-" },
      LEGENDARY: { min: 5, max: 8 },
      MYSTIC: { min: 9, max: 15 },
    },
  },
  {
    key: "EXP_GAIN",
    label: "EXP Gain",
    flat: false,
    values: {
      NORMAL: { void: "-" },
      RARE: { void: "-" },
      EPIC: { void: "-" },
      UNIQUE: { void: "-" },
      LEGENDARY: { min: 5, max: 8 },
      MYSTIC: { min: 9, max: 15 },
    },
  },
  {
    key: "DEFENSE_PENETRATION",
    label: "Defense Penetration",
    flat: false,
    values: {
      NORMAL: { void: "-" },
      RARE: { void: "-" },
      EPIC: { void: "-" },
      UNIQUE: { void: "-" },
      LEGENDARY: { min: 8, max: 12 },
      MYSTIC: { min: 14, max: 20 },
    },
  },
  {
    key: "BOSS_DAMAGE",
    label: "Boss Monster Damage",
    flat: false,
    values: {
      NORMAL: { void: "-" },
      RARE: { void: "-" },
      EPIC: { void: "-" },
      UNIQUE: { void: "-" },
      LEGENDARY: { min: 18, max: 25 },
      MYSTIC: { min: 28, max: 40 },
    },
  },
  {
    key: "NORMAL_MONSTER_DAMAGE",
    label: "Normal Monster Damage",
    flat: false,
    values: {
      NORMAL: { void: "-" },
      RARE: { void: "-" },
      EPIC: { void: "-" },
      UNIQUE: { void: "-" },
      LEGENDARY: { min: 18, max: 25 },
      MYSTIC: { min: 28, max: 40 },
    },
  },
];
